"use client";
import { useState } from "react";
import { Copy, KeyRound, Pencil, Plus, Save, Trash2, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { useFetch } from "@/lib/use-fetch";
import { apiFetch, del, postJson, putJson } from "@/lib/api";
import { PERMISSIONS, dateTime, type DevCompany, type Invite } from "@/lib/dev";
import { ConfirmAction, DevHeading, Field, LoadView, selectClass, TableWrap } from "./shared";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
const empty = { id: 0, name: "", industry: "", website: "", location: "", size: "", about: "", contact_email: "", active: true, knowledge: "" };

export function CompaniesView() {
  const query = useFetch<DevCompany[]>("/api/dev/companies");
  const invites = useFetch<Invite[]>("/api/dev/invites");
  const [editing, setEditing] = useState<DevCompany | null>(null);
  return <><DevHeading title="Companies" label="Workspace administration" refresh={query.reload} action={<Button onClick={() => setEditing({ ...empty })}><Plus className="size-4" />Create company</Button>} /><LoadView {...query}>{companies => <>
    <TableWrap><table><thead><tr><th>Company</th><th>Industry</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{companies.map(c => <tr key={c.id}><td className="font-semibold">{c.name}<span className="ml-2 text-xs font-normal text-muted-foreground">#{c.id}</span></td><td>{c.industry || "-"}</td><td>{c.location || "-"}</td><td><span className={c.active ? "text-emerald-600 dark:text-emerald-400" : "text-rose-500"}>{c.active ? "Active" : "Suspended"}</span></td><td><div className="flex gap-2"><Button size="icon" variant="ghost" title="Edit company" aria-label={`Edit ${c.name}`} onClick={() => setEditing(c)}><Pencil /></Button><ConfirmAction title={`Delete ${c.name}?`} description="Only companies without members, jobs or invitations can be deleted." onConfirm={async () => { await del(`/api/dev/companies/${c.id}`); query.reload(); }}><Trash2 className="size-4" /></ConfirmAction></div></td></tr>)}</tbody></table>{!companies.length && <p className="p-8 text-center text-sm text-muted-foreground">No companies yet</p>}</TableWrap>
    {editing && <CompanyEditor key={editing.id} initial={editing} close={() => setEditing(null)} saved={() => { setEditing(null); query.reload(); }} />}
    <section className="border-t pt-7"><h2 className="mb-5 text-xl font-semibold">Invite code studio</h2><InviteForm companies={companies} onSaved={invites.reload} /><LoadView {...invites}>{rows => <TableWrap><table><thead><tr>{["Email", "Company", "Expires", "Status", "Actions"].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(i => <tr key={i.id}><td>{i.email}</td><td>{companies.find(c => c.id === i.company_id)?.name || i.company_id}</td><td>{dateTime(i.expires_at)}</td><td>{i.accepted_at ? "Accepted" : new Date(/Z$|[+-]\d\d:\d\d$/.test(i.expires_at) ? i.expires_at : `${i.expires_at}Z`) < new Date() ? "Expired" : "Pending"}</td><td>{!i.accepted_at && <ConfirmAction title="Revoke invitation?" description={`The invitation for ${i.email} will stop working.`} onConfirm={async () => { await del(`/api/dev/invites/${i.id}`); invites.reload(); }}><X className="size-4" />Revoke</ConfirmAction>}</td></tr>)}</tbody></table></TableWrap>}</LoadView></section>
  </>}</LoadView></>;
}
function CompanyEditor({ initial, saved, close }: { initial: DevCompany; saved: () => void; close: () => void }) {
  const [company, setCompany] = useState(initial), [busy, setBusy] = useState(false);
  async function upload(file?: File) {
    if (!file) return;
    setBusy(true);
    const body = new FormData(); body.append("file", file);
    try { const result = await apiFetch<{ knowledge: string }>(`/api/dev/companies/${company.id}/knowledge`, { method: "POST", body }); setCompany({ ...company, knowledge: result.knowledge }); toast.success("Knowledge file saved"); } catch (error) { toast.error((error as Error).message); } finally { setBusy(false); }
  }
  return <form className="space-y-5 border-y py-6" onSubmit={async e => { e.preventDefault(); setBusy(true); try { if (company.id) await putJson(`/api/dev/companies/${company.id}`, company); else await postJson("/api/dev/companies", company); toast.success("Company saved"); saved(); } catch (error) { toast.error((error as Error).message); } finally { setBusy(false); } }}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{company.id ? "Edit company" : "New company"}</h2><Button variant="ghost" size="icon" type="button" onClick={close} title="Close editor" aria-label="Close editor"><X /></Button></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{([ ["name", "Company name"], ["industry", "Industry"], ["location", "Location"], ["website", "Website"], ["contact_email", "Contact email"] ] as const).map(([key, label]) => <Field key={key} id={`dev-company-${key}`} label={label}><Input id={`dev-company-${key}`} required={key === "name"} type={key === "website" ? "url" : key === "contact_email" ? "email" : "text"} value={company[key]} onChange={e => setCompany({ ...company, [key]: e.target.value })} /></Field>)}<Field id="dev-company-size" label="Company size"><select id="dev-company-size" className={`${selectClass} w-full`} value={company.size} onChange={e => setCompany({ ...company, size: e.target.value })}><option value="">Not specified</option>{["1-10", "11-50", "51-200", "201-500", "501-1000", "1000+"].map(s => <option key={s}>{s}</option>)}</select></Field></div><Field id="dev-company-about" label="About company"><Textarea id="dev-company-about" value={company.about} onChange={e => setCompany({ ...company, about: e.target.value })} rows={4} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={company.active} onChange={e => setCompany({ ...company, active: e.target.checked })} />Active workspace</label>{company.id > 0 && <section className="space-y-3 border-t pt-4"><label className="flex items-center gap-2 text-sm font-medium" htmlFor="knowledge-file"><Upload className="size-4" />company_info.md</label><Input id="knowledge-file" type="file" accept=".md" disabled={busy} onChange={e => upload(e.target.files?.[0])} />{company.knowledge && <pre className="max-h-48 overflow-auto whitespace-pre-wrap break-words border p-3 text-xs">{company.knowledge}</pre>}</section>}<Button type="submit" disabled={busy}><Save className="size-4" />{busy ? "Saving..." : "Save company"}</Button></form>;
}
function InviteForm({ companies, onSaved }: { companies: DevCompany[]; onSaved: () => void }) {
  const [email, setEmail] = useState(""), [company, setCompany] = useState(""), [days, setDays] = useState(7), [permissions, setPermissions] = useState(PERMISSIONS.slice(0, -1));
  const [code, setCode] = useState(""), [busy, setBusy] = useState(false);
  return <form className="mb-6 space-y-5" onSubmit={async e => { e.preventDefault(); setBusy(true); setCode(""); try { const result = await postJson<{ code: string }>("/api/dev/invites", { email, company_id: Number(company), days, permissions }); setCode(result.code); onSaved(); toast.success("Invitation generated"); } catch (error) { toast.error((error as Error).message); } finally { setBusy(false); } }}><div className="grid items-end gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field id="invite-company" label="Company"><select id="invite-company" required className={`${selectClass} w-full`} value={company} onChange={e => setCompany(e.target.value)}><option value="">Select company</option>{companies.filter(c => c.active).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field id="invite-email" label="Recruiter email"><Input id="invite-email" required type="email" value={email} onChange={e => setEmail(e.target.value)} /></Field><Field id="invite-days" label="Expires in days"><Input id="invite-days" type="number" required min={1} max={30} value={days} onChange={e => setDays(Number(e.target.value))} /></Field><Button type="submit" disabled={busy}><KeyRound className="size-4" />Generate invite</Button></div><div className="flex flex-wrap gap-x-6 gap-y-3">{PERMISSIONS.map(permission => <label key={permission} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={permissions.includes(permission)} onChange={e => setPermissions(e.target.checked ? [...permissions, permission] : permissions.filter(p => p !== permission))} />{permission}</label>)}</div>{code && <div className="flex flex-wrap items-center gap-3 rounded-md border border-emerald-500/40 bg-emerald-500/5 p-4"><code className="min-w-0 flex-1 break-all text-sm">{code}</code><Button variant="outline" size="icon" title="Copy invitation code" aria-label="Copy invitation code" type="button" onClick={() => navigator.clipboard.writeText(code).then(() => toast.success("Copied")).catch(() => toast.error("Clipboard unavailable"))}><Copy /></Button></div>}</form>;
}
