"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, Save, Search, Settings2, X } from "lucide-react";
import { toast } from "sonner";
import { useFetch } from "@/lib/use-fetch";
import { patchJson, postJson } from "@/lib/api";
import { useAuth, type AuthUser } from "@/lib/auth-context";
import { PERMISSIONS, type DevUser } from "@/lib/dev";
import { DevHeading, Field, LoadView, selectClass, TableWrap } from "./shared";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { UserCreator, UserOperations } from "./user-management";

export function UsersView() {
  const [search, setSearch] = useState(""), [offset, setOffset] = useState(0);
  const [roleFilter, setRoleFilter] = useState(""), [accessFilter, setAccessFilter] = useState("");
  const [editing, setEditing] = useState<DevUser | null>(null), [viewing, setViewing] = useState<DevUser | null>(null);
  const query = useFetch<DevUser[]>(`/api/dev/users?q=${encodeURIComponent(search)}&offset=${offset}${roleFilter ? `&role=${roleFilter}` : ""}${accessFilter ? `&disabled=${accessFilter}` : ""}`);
  return <><DevHeading title="Users & access" label="Identity / Permissions / Support" refresh={query.reload} /><UserCreator onSaved={query.reload} /><div className="relative max-w-lg"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input aria-label="Search users" placeholder="Search by name or email" className="pl-9" value={search} onChange={e => { setSearch(e.target.value); setOffset(0); }} /></div><div className="flex flex-wrap gap-3"><select aria-label="Filter user role" className={selectClass} value={roleFilter} onChange={e => { setRoleFilter(e.target.value); setOffset(0); }}><option value="">All roles</option>{["candidate", "recruiter", "developer", "superadmin"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter user access" className={selectClass} value={accessFilter} onChange={e => { setAccessFilter(e.target.value); setOffset(0); }}><option value="">All access states</option><option value="false">Active</option><option value="true">Revoked</option></select></div><LoadView {...query}>{users => <><TableWrap><table><thead><tr>{["User", "Role", "Company", "Access", "Actions"].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{users.map(user => <tr key={user.id}><td><p className="font-medium">{user.full_name || "Unnamed user"} <span className="text-xs font-normal text-muted-foreground">#{user.id}</span></p><p className="mt-1 text-xs text-muted-foreground">{user.email}</p></td><td className="capitalize">{user.role}</td><td>{user.company_id ? `#${user.company_id}` : "-"}</td><td className={user.disabled ? "text-rose-500" : "text-emerald-600 dark:text-emerald-400"}>{user.disabled ? "Revoked" : "Active"}</td><td><div className="flex gap-2"><Button variant="ghost" size="icon" title="Manage access" aria-label={`Manage ${user.email}`} onClick={() => { setEditing(user); setViewing(null); }}><Settings2 /></Button>{!["developer", "superadmin"].includes(user.role) && !user.disabled && <Button variant="outline" onClick={() => { setViewing(user); setEditing(null); }}><Eye className="size-4" />Impersonate</Button>}</div></td></tr>)}</tbody></table></TableWrap><div className="flex justify-between"><Button variant="outline" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 100))}>Previous</Button><Button variant="outline" disabled={users.length < 100} onClick={() => setOffset(offset + 100)}>Next</Button></div></>}</LoadView>{editing && <UserEditor key={editing.id} initial={editing} saved={() => { setEditing(null); query.reload(); }} close={() => setEditing(null)} />}{viewing && <ImpersonateForm key={viewing.id} target={viewing} close={() => setViewing(null)} />}</>;
}
function UserEditor({ initial, saved, close }: { initial: DevUser; saved: () => void; close: () => void }) {
  const { user } = useAuth();
  const [form, setForm] = useState(initial), [reason, setReason] = useState(""), [busy, setBusy] = useState(false);
  return <><form className="space-y-5 border-t pt-6" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await patchJson(`/api/dev/users/${form.id}`, { role: form.role, disabled: form.disabled, permissions: form.permissions, reason }); toast.success("Access updated; existing sessions revoked"); saved(); } catch (error) { toast.error((error as Error).message); } finally { setBusy(false); } }}><div className="flex justify-between gap-3"><h2 className="break-all text-xl font-semibold">{form.email}</h2><Button type="button" variant="ghost" size="icon" onClick={close} aria-label="Close access editor"><X /></Button></div><div className="flex flex-wrap items-end gap-6"><Field id="user-role" label="Role"><select id="user-role" className={selectClass} value={form.role} onChange={e => setForm({ ...form, role: e.target.value as AuthUser["role"] })}>{(user?.role === "superadmin" ? ["candidate", "recruiter", "developer", "superadmin"] : ["candidate", "recruiter"]).map(r => <option key={r}>{r}</option>)}</select></Field><label className="flex items-center gap-2 pb-2 text-sm"><input type="checkbox" checked={form.disabled} onChange={e => setForm({ ...form, disabled: e.target.checked })} />Revoke access</label></div>{form.role === "recruiter" && <fieldset className="flex flex-wrap gap-5"><legend className="mb-3 text-sm font-medium">Company permissions</legend>{PERMISSIONS.map(p => <label key={p} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.permissions.includes(p)} onChange={e => setForm({ ...form, permissions: e.target.checked ? [...form.permissions, p] : form.permissions.filter(v => v !== p) })} />{p}</label>)}</fieldset>}<Field id="access-reason" label="Reason for change"><Textarea id="access-reason" required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></Field><Button type="submit" disabled={busy || form.id === user?.id}><Save className="size-4" />Save access</Button></form><UserOperations initial={initial} saved={saved} /></>;
}
function ImpersonateForm({ target, close }: { target: DevUser; close: () => void }) {
  const { user, token, login } = useAuth();
  const router = useRouter();
  const [role, setRole] = useState(target.role), [reason, setReason] = useState(""), [busy, setBusy] = useState(false);
  return <form className="space-y-4 border-t pt-6" onSubmit={async e => { e.preventDefault(); setBusy(true); try { const result = await postJson<{ access_token: string; user: AuthUser }>(`/api/dev/users/${target.id}/impersonate`, { role, reason }); sessionStorage.setItem("dev_return_session", JSON.stringify({ token, user })); login(result.access_token, result.user); router.push(role === "candidate" ? "/candidate/jobs" : "/recruiter/dashboard"); } catch (error) { toast.error((error as Error).message); setBusy(false); } }}><h2 className="break-all text-xl font-semibold">Support session: {target.email}</h2><p className="text-sm text-amber-700 dark:text-amber-300">15-minute session. Changes affect this account and are audited.</p><Field id="impersonation-role" label="Workspace"><select id="impersonation-role" className={selectClass} value={role} onChange={e => setRole(e.target.value as AuthUser["role"])}>{target.role === "recruiter" && <option value="recruiter">Recruiter</option>}{target.candidate_id && <option value="candidate">Candidate</option>}{target.role === "candidate" && !target.candidate_id && <option value="candidate">Candidate</option>}</select></Field><Field id="impersonation-reason" label="Support reason"><Textarea id="impersonation-reason" required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></Field><div className="flex gap-3"><Button type="submit" disabled={busy}><Eye className="size-4" />Start support session</Button><Button type="button" variant="outline" onClick={close}>Cancel</Button></div></form>;
}
