"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Download, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { downloadFile, postJson } from "@/lib/api";
import { useFetch } from "@/lib/use-fetch";
import { dateLabel, statusLabels, type Application, type Assessment } from "@/lib/portal";
import { Button, buttonVariants } from "@/components/ui/button";
import { ErrorState } from "@/components/states";
import { LoadingPortal, PortalHeading, StatusBadge } from "@/components/portal-shared";
import { ApplicationConversation } from "@/components/application-conversation";
import { CandidateInterviews } from "@/components/candidate-interviews";

export function CandidateApplications() {
  const { state, reload } = useFetch<Application[]>("/api/portal/applications");
  const [filter, setFilter] = useState("all");
  const apps = state.status === "ready" ? state.data.filter(a => filter === "all" || a.status === filter) : [];
  return <><PortalHeading title="My applications" description="Your progress, feedback and conversations for every role." action={<Link href="/candidate/jobs" className={buttonVariants({ variant: "outline" })}>Find jobs <ArrowRight className="size-4" /></Link>} />
    {state.status === "ready" && <div className="mb-7 grid grid-cols-3 divide-x border-y py-5">{[["Applications", state.data.length], ["In progress", state.data.filter(a => !["withdrawn", "rejected", "hired"].includes(a.status)).length], ["Offers", state.data.filter(a => a.status === "offer").length]].map(([label, value]) => <div key={label} className="px-4 first:pl-0"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div>}
    <div className="mb-5 flex items-center justify-between gap-3"><label className="flex flex-wrap items-center gap-3 text-sm">Status<select className="h-9 rounded-md border bg-background px-3" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All applications</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><Button variant="ghost" size="icon" title="Refresh applications" aria-label="Refresh applications" onClick={reload}><RefreshCw /></Button></div>
    {state.status === "loading" ? <LoadingPortal /> : state.status === "error" ? <ErrorState message={state.message} onRetry={reload} /> : !apps.length ? <div className="border-t py-16 text-center"><h2 className="font-semibold">No applications here yet</h2><Link href="/candidate/jobs" className="mt-3 inline-block text-sm text-primary">Browse open jobs</Link></div> : <div className="divide-y border-t">{apps.map(app => <article key={app.id} className="flex flex-wrap items-center justify-between gap-4 py-6"><div className="min-w-0"><Link href={`/candidate/applications/${app.id}`} className="break-words text-lg font-semibold hover:text-primary">{app.job_title}</Link><p className="mt-2 text-xs text-muted-foreground">Applied {dateLabel(app.created_at)} · Updated {dateLabel(app.updated_at)}</p><p className="mt-2 text-sm text-muted-foreground">{app.history.at(-1)?.note}</p></div><div className="flex flex-wrap items-center gap-4"><StatusBadge status={app.status} /><span className="text-sm tabular-nums">{app.assessment ? `${app.assessment.overall_score}/100 match` : "Match pending"}</span><Link href={`/candidate/applications/${app.id}`} title="View application" aria-label={`View ${app.job_title}`} className={buttonVariants({ variant: "outline", size: "icon" })}><ArrowRight /></Link></div></article>)}</div>}
  </>;
}

export function CandidateApplicationDetail({ applicationId }: { applicationId: string }) {
  const { state, reload, update } = useFetch<Application>(`/api/portal/applications/${applicationId}`);
  const cohort = useFetch<{ rank: number | null; assessed_count: number; top_percent?: number | null; note: string }>(`/api/portal/applications/${applicationId}/cohort`);
  const [tab, setTab] = useState("overview");
  const [busy, setBusy] = useState(false);
  const [confirmWithdraw, setConfirmWithdraw] = useState(false);
  async function action(type: "evaluate" | "withdraw") {
    setBusy(true);
    try { const result = await postJson<Application>(`/api/portal/applications/${applicationId}/${type}`); update(() => result); setConfirmWithdraw(false); toast.success(type === "evaluate" ? "Match assessment ready" : "Application withdrawn"); }
    catch (error) { toast.error((error as Error).message); } finally { setBusy(false); }
  }
  if (state.status === "loading") return <LoadingPortal />;
  if (state.status === "error") return <ErrorState message={state.message} onRetry={reload} />;
  const app = state.data;
  const closed = ["withdrawn", "rejected", "hired"].includes(app.status);
  return <><Link href="/candidate/applications" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />My applications</Link><PortalHeading title={app.job_title} description={`Application #${app.id} · Submitted ${dateLabel(app.created_at)}`} action={<StatusBadge status={app.status} />} />
    <div role="tablist" aria-label="Application sections" className="mb-7 flex gap-1 overflow-x-auto border-b">{[["overview", "Application status"], ["match", "Match & scores"], ["messages", "Messages"]].map(([value, label]) => <button role="tab" aria-selected={tab === value} aria-controls={`panel-${value}`} id={`tab-${value}`} key={value} onClick={() => setTab(value)} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-medium ${tab === value ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>{label}</button>)}</div>
    <div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
      {tab === "overview" && <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_320px]"><section><h2 className="mb-5 text-lg font-semibold">Current stage: {statusLabels[app.status]}</h2><ol className="space-y-0">{app.history.map((event, index) => <li key={index} className="relative ml-2 border-l pb-7 pl-6"><span className={`absolute -left-1.5 top-1.5 size-3 rounded-full ${index === app.history.length - 1 ? "bg-primary" : "bg-muted-foreground/40"}`} /><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{statusLabels[event.status]}</h3><time className="text-xs text-muted-foreground">{dateLabel(event.at)}</time></div><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-muted-foreground">{event.note}</p></li>)}</ol><Button variant="outline" onClick={reload}><RefreshCw className="size-4" />Refresh status</Button></section><section className="space-y-5 border-t pt-5 lg:border-t-0 lg:border-l lg:pl-7 lg:pt-0"><h2 className="text-lg font-semibold">Submitted details</h2><div><p className="mb-2 text-xs text-muted-foreground">Resume</p><button onClick={() => downloadFile(`/api/portal/resumes/${app.resume_id}/download`, app.resume_name).catch(e => toast.error(e.message))} className="inline-flex max-w-full items-center gap-2 text-sm text-primary"><Download className="size-4 shrink-0" /><span className="break-all text-left">{app.resume_name}</span></button></div>{app.cover_letter && <div><h3 className="mb-2 text-xs text-muted-foreground">Cover letter</h3><p className="whitespace-pre-wrap break-words text-sm leading-6">{app.cover_letter}</p></div>}<p className="text-xs text-muted-foreground">Submitted resume versions remain attached to this application.</p>{!closed && <Button variant="outline" onClick={() => setConfirmWithdraw(true)}>Withdraw application</Button>}{confirmWithdraw && <div role="alert" className="space-y-3 border-t pt-4"><p className="text-sm">Withdraw this application? You cannot apply to this role again with this account.</p><div className="flex gap-2"><Button variant="destructive" disabled={busy} onClick={() => action("withdraw")}>Confirm withdrawal</Button><Button variant="ghost" onClick={() => setConfirmWithdraw(false)}>Cancel</Button></div></div>}</section></div>}
      {tab === "match" && (app.assessment ? <><MatchExplanation assessment={app.assessment} /><section className="mt-8 border-t pt-6"><h2 className="font-semibold">Your position in this applicant group</h2>{cohort.state.status === "ready" && <><p className="mt-2 text-2xl font-semibold tabular-nums">{cohort.state.data.rank ? `#${cohort.state.data.rank} of ${cohort.state.data.assessed_count}` : "Not ranked yet"}</p><p className="mt-2 text-sm text-muted-foreground">{cohort.state.data.note}</p></>}{cohort.state.status === "error" && <p className="mt-2 text-sm text-muted-foreground">Anonymous ranking is not available right now.</p>}</section></> : <section className="py-10"><h2 className="text-lg font-semibold">Match assessment pending</h2><p className="mb-5 mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Your application has been received. No score has been assigned yet.</p>{!closed && <Button disabled={busy} onClick={() => action("evaluate")}><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`} />{busy ? "Assessing your resume..." : "Request match assessment"}</Button>}</section>)}
      {tab === "overview" && <CandidateInterviews applicationId={app.id} />}
      {tab === "messages" && <div className="max-w-3xl"><ApplicationConversation applicationId={app.id} /></div>}
    </div></>;
}

const explanations = {
  skills: { label: "Skills coverage", reason: "Required and preferred skills found in the submitted resume. Demonstrated skills receive more credit than skills that are only listed." },
  semantic: { label: "Role relevance", reason: "Similarity between the role requirements and the professional experience described in the submitted resume." },
  experience: { label: "Relevant experience", reason: "Experience duration compared with the job minimum, adjusted for relevance to this role." },
  ai_review: { label: "Resume review", reason: "A review of skills evidence and domain fit. Skills account for 60% of this component and domain fit for 40%." },
} as const;
export function MatchExplanation({ assessment: a, title = "Why you received this score" }: { assessment: Assessment; title?: string }) {
  return <div className="space-y-8"><section className="flex flex-wrap items-start gap-8 border-b pb-7"><div className="min-w-32"><p className="text-sm text-muted-foreground">Overall match</p><p className="mt-2 text-4xl font-semibold tabular-nums">{a.overall_score}<span className="text-lg font-normal text-muted-foreground"> / 100</span></p></div><div className="max-w-3xl"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-7">{a.summary || "No overall explanation was provided."}</p><p className="mt-3 text-xs text-muted-foreground">Assessed {dateLabel(a.evaluated_at)} · Resume match is separate from the hiring decision.</p></div></section>
    <section><h2 className="mb-5 text-lg font-semibold">Marks by criterion</h2><div className="divide-y">{Object.entries(explanations).map(([key, definition]) => { const score = a.breakdown[key as keyof typeof explanations]; const weight = a.weights[key as keyof typeof explanations] ?? 0; return <div key={key} className="grid gap-4 py-5 sm:grid-cols-[180px_minmax(0,1fr)_110px]"><div><h3 className="font-medium">{definition.label}</h3><p className="mt-1 text-xs text-muted-foreground">{score == null ? "Not scored" : `${(weight * 100).toFixed(1)}% weight`}</p></div><div><p className="text-sm leading-6 text-muted-foreground">{definition.reason}</p>{key === "experience" && <p className="mt-2 text-xs">Resume experience: {a.years_experience} years · Job minimum: {a.minimum_years} years</p>}{score != null && <progress aria-label={`${definition.label} score`} max={100} value={score} className="mt-3 h-2 w-full accent-emerald-600" />}</div><div className="text-left sm:text-right"><p className="font-semibold tabular-nums">{score == null ? "N/A" : `${score}/100`}</p>{score != null && <p className="mt-1 text-xs text-muted-foreground">{(score * weight).toFixed(1)} overall points</p>}</div></div>; })}</div></section>
    <div className="grid gap-8 sm:grid-cols-2"><section><h2 className="mb-4 text-lg font-semibold">Strengths</h2><ul className="list-disc space-y-2 pl-5 text-sm leading-6">{a.strengths.map(s => <li key={s}>{s}</li>)}</ul>{!a.strengths.length && <p className="text-sm text-muted-foreground">None recorded.</p>}</section><section><h2 className="mb-4 text-lg font-semibold">Areas to improve</h2><ul className="list-disc space-y-2 pl-5 text-sm leading-6">{a.gaps.map(s => <li key={s}>{s}</li>)}</ul>{!a.gaps.length && <p className="text-sm text-muted-foreground">None recorded.</p>}</section></div>
    <section><h2 className="mb-4 text-lg font-semibold">Skill evidence</h2><div className="divide-y border-t">{a.skill_details.map((s, i) => <div key={i} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span>{s.skill} <span className="text-xs text-muted-foreground">({s.kind === "must" ? "required" : "preferred"})</span></span><span className={s.status === "missing" ? "text-amber-700 dark:text-amber-400" : "text-primary"}>{s.status === "demonstrated" ? "Demonstrated in experience" : s.status === "listed" ? "Listed in resume" : "Not found in resume"}</span></div>)}</div></section>
    <section><h2 className="mb-4 text-lg font-semibold">Evidence behind the review</h2>{a.evidence.length ? a.evidence.map((e, i) => <div key={i} className="mb-5 border-l-2 border-primary pl-4"><h3 className="text-sm font-medium">{e.claim}</h3><blockquote className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-muted-foreground">{e.quote}</blockquote></div>) : <p className="text-sm text-muted-foreground">No verified resume quotations were recorded.</p>}</section>
  </div>;
}
