import { useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Bell, BriefcaseBusiness, CalendarDays, ChartNoAxesCombined, Check, ChevronDown, ChevronsUpDown, CircleHelp, Code2, Command, FileText, LayoutDashboard, Menu, Search, Settings2, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import profile from '@/assets/profile.jpg';
import { candidates, type Persona, type Section } from './data';

export function Avatar({ index = 0, large = false }: { index?: number; large?: boolean }) {
  return index === 0 ? <img className={`avatar ${large ? 'large' : ''}`} src={profile} alt="Priya Sharma" width={32} height={32} /> : <span className={`avatar avatar-initials tone-${index % 4}`}>{candidates[index % candidates.length]?.initials ?? 'HK'}</span>;
}
export function WorkspaceShell({ children, persona = 'hr', section }: { children: ReactNode; persona?: Persona; section?: Section }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState('');
  const label = persona === 'hr' ? 'HR workspace' : persona === 'candidate' ? 'Candidate workspace' : 'Developer admin';
  const nav = [{ id: 'candidates', name: 'Candidates', icon: Users, count: '1,284' }, { id: 'jobs', name: 'Jobs', icon: BriefcaseBusiness, count: '12' }, { id: 'interviews', name: 'Interviews', icon: CalendarDays }, { id: 'ai-insights', name: 'AI Insights', icon: Sparkles }, { id: 'analytics', name: 'Analytics', icon: ChartNoAxesCombined }] as const;
  return <div className="app-layout">
    <aside className={`app-sidebar ${mobileOpen ? 'mobile-open' : ''}`}>
      <Link to="/" className="brand"><span className="brand-mark"><ChartNoAxesCombined size={21} strokeWidth={2.8} /></span>hirely<span className="text-primary">.</span></Link>
      <Popover><PopoverTrigger asChild><Button variant="ghost" className="workspace-switch" aria-label="Switch workspace"><span className="flex items-center gap-2.5"><span className="workspace-icon">h.</span><span className="text-left"><span className="block text-xs font-semibold">Acme Technologies</span><span className="block text-[10px] text-muted-foreground mt-1">{label}</span></span></span><ChevronsUpDown className="text-muted-foreground" size={13} /></Button></PopoverTrigger><PopoverContent className="role-menu" align="start"><Link to="/" className="role-option"><Users size={16} /> HR workspace {persona === 'hr' && <Check size={13} className="ml-auto text-primary" />}</Link><Link to="/candidate" className="role-option"><FileText size={16} /> Candidate workspace {persona === 'candidate' && <Check size={13} className="ml-auto text-primary" />}</Link><Link to="/admin" className="role-option"><Code2 size={16} /> Developer admin {persona === 'admin' && <Check size={13} className="ml-auto text-primary" />}</Link></PopoverContent></Popover>
      <nav aria-label="Main navigation">
        <Link to={persona === 'hr' ? '/' : persona === 'candidate' ? '/candidate' : '/admin'} className={`nav-link ${!section ? 'active' : ''}`}><LayoutDashboard size={17} />Overview</Link>
        <div className="nav-label">{persona === 'hr' ? 'Recruitment' : persona === 'candidate' ? 'Your next chapter' : 'Platform'}</div>
        {persona === 'hr' ? nav.map(({ id, name, icon: Icon, ...item }, index) => <div key={id}>{index === 3 && <div className="nav-label">Intelligence</div>}<Link to="/workspace/$section" params={{ section: id }} className={`nav-link ${section === id ? 'active' : ''}`}><Icon size={17} />{name}{'count' in item && <span className="nav-count">{item.count}</span>}{id === 'ai-insights' && <span className="ml-auto text-[9px] text-primary">NEW</span>}</Link></div>) : persona === 'candidate' ? <><Link to="/candidate" hash="applications" activeOptions={{ includeHash: true }} className="nav-link"><FileText size={17} />My applications<span className="nav-count">3</span></Link><Link to="/candidate" hash="opportunities" activeOptions={{ includeHash: true }} className="nav-link"><BriefcaseBusiness size={17} />Discover jobs</Link><Link to="/candidate" hash="applications" activeOptions={{ includeHash: true }} className="nav-link"><CalendarDays size={17} />Interviews</Link><Link to="/candidate" hash="profile" activeOptions={{ includeHash: true }} className="nav-link"><Users size={17} />My profile</Link></> : <><Link to="/admin" hash="organizations" activeOptions={{ includeHash: true }} className="nav-link"><BriefcaseBusiness size={17} />Organizations</Link><Link to="/admin" hash="services" activeOptions={{ includeHash: true }} className="nav-link"><ShieldCheck size={17} />System health</Link><Link to="/admin" hash="activity" activeOptions={{ includeHash: true }} className="nav-link"><Code2 size={17} />Activity logs</Link></>}
      </nav>
      <div className="sidebar-bottom"><Link to="/workspace/$section" params={{ section: 'settings' }} className={`nav-link ${section === 'settings' ? 'active' : ''}`}><Settings2 size={17} />Settings</Link><Popover><PopoverTrigger asChild><Button variant="ghost" className="nav-link w-full justify-start"><CircleHelp size={17} />Help & resources<ArrowUpRight size={13} className="ml-auto" /></Button></PopoverTrigger><PopoverContent className="text-xs leading-6"><strong>Hirely workspace</strong><p className="text-muted-foreground">Contact your workspace administrator for account and recruitment support.</p><p className="text-muted-foreground mt-2">Preview version · Sample data</p></PopoverContent></Popover><div className="user-row"><Avatar /><span className="flex-1"><strong className="text-[11px] font-semibold">{persona === 'candidate' ? 'Priya Sharma' : 'Harsh Kumar'}</strong><span className="block text-[10px] text-muted-foreground mt-1">{persona === 'hr' ? 'HR Manager' : persona === 'candidate' ? 'Product Designer' : 'Platform administrator'}</span></span><ChevronDown size={13} className="text-muted-foreground" /></div></div>
    </aside>
    <div className="min-w-0"><header className="app-topbar"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="mobile-menu" aria-label={mobileOpen ? 'Close menu' : 'Open menu'} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</Button><span className="text-muted-foreground text-xs">Workspace <span className="px-2 text-muted-foreground/50">/</span> <span className="text-foreground">{section ? nav.find(x => x.id === section)?.name ?? 'Settings' : 'Overview'}</span></span></div><div className="flex gap-5 items-center"><Button variant="ghost" className="search-trigger" onClick={() => setSearchOpen(true)}><Search size={15} />Search anything...<span className="keycap">⌘ K</span></Button><span className="h-5 border-l border-border" /><Popover><PopoverTrigger asChild><Button variant="ghost" size="icon" aria-label="Notifications" className="relative"><Bell size={17} /><span className="absolute right-2 top-2 size-1 rounded-full bg-primary" /></Button></PopoverTrigger><PopoverContent align="end"><strong className="text-xs">You're all caught up</strong><p className="text-muted-foreground mt-2 text-xs">Your workspace notifications will appear here.</p></PopoverContent></Popover><Avatar /></div></header><main className="page-content">{children}<footer className="page-footer"><span>Thoughtful hiring. Exceptional teams.</span><span className="flex items-center gap-4"><span>Sample workspace</span><span><span className="live-dot" />All systems operational</span></span></footer></main></div>
    <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent><DialogHeader><DialogTitle>Search workspace</DialogTitle></DialogHeader><input className="text-input w-full" placeholder="Search candidates, roles..." value={query} onChange={e => setQuery(e.target.value)} autoFocus /><div>{candidates.filter(c => `${c.name} ${c.role}`.toLowerCase().includes(query.toLowerCase())).map((c, i) => <Link key={c.id} to="/candidates/$candidateId" params={{ candidateId: c.id }} onClick={() => setSearchOpen(false)} className="role-option"><Avatar index={i} /><span>{c.name}<small className="block text-muted-foreground">{c.role}</small></span><ArrowUpRight size={15} className="ml-auto" /></Link>)}</div></DialogContent></Dialog>
  </div>;
}