"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, Plus } from "lucide-react";
import { useFetch } from "@/lib/use-fetch";
import { formatDateTime, type RecruiterDashboard } from "@/lib/recruiter";
import { dateLabel, statusLabels } from "@/lib/portal";
import { PortalHeading, StatusBadge } from "@/components/portal-shared";
import { LoadView } from "@/components/recruiter/shared";
import { buttonVariants } from "@/components/ui/button";

export function RecruiterDashboardView() {
  const query = useFetch<RecruiterDashboard>("/api/recruiter/dashboard");
  return <LoadView {...query}>{data => <>
    <PortalHeading title="Recruiter dashboard" description={data.company.name || "Your hiring activity at a glance."} action={<Link href="/recruiter/jobs/new" className={buttonVariants()}><Plus className="size-4" />Create job</Link>} />
    {!data.company.name && <div className="mb-7 flex flex-wrap items-center justify-between gap-4 border-y bg-amber-50 px-4 py-4 text-sm text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"><p>Add your company details before publishing your first job.</p><Link href="/recruiter/company" className="inline-flex items-center gap-2 font-semibold">Complete company profile <ArrowRight className="size-4" /></Link></div>}
    <div className="mb-9 grid grid-cols-2 gap-y-6 border-y py-6 md:grid-cols-4">{[["Open jobs", data.open_jobs, "/recruiter/jobs"], ["Applicants", data.applications, "/recruiter/applicants"], ["Shortlisted", data.shortlisted, "/recruiter/applicants?status=shortlisted"], ["Awaiting assessment", data.pending_review, "/recruiter/applicants"]].map(([label, count, href]) => <Link key={label} href={String(href)} className="border-l px-5 first:border-l-0 first:pl-0"><p className="text-3xl font-semibold tabular-nums">{count}</p><p className="mt-2 text-sm text-muted-foreground">{label}</p></Link>)}</div>
    <div className="grid gap-10 xl:grid-cols-[minmax(0,1fr)_320px]"><section><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Recent applicants</h2><Link href="/recruiter/applicants" className="text-sm text-primary">View all</Link></div>{!data.recent_applicants.length ? <p className="border-t py-12 text-sm text-muted-foreground">Applications will appear here once candidates apply to your jobs.</p> : <div className="divide-y border-t">{data.recent_applicants.map(a => <Link href={`/recruiter/applicants/${a.id}`} key={a.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><h3 className="font-medium">{a.candidate_name}</h3><p className="mt-1 text-xs text-muted-foreground">{a.job_title} · {dateLabel(a.created_at)}</p></div><StatusBadge status={a.status} /></Link>)}</div>}</section><section><h2 className="mb-5 text-lg font-semibold">Hiring pipeline</h2><div className="space-y-4 border-t pt-5">{Object.entries(data.stages).filter(([stage]) => !["rejected", "withdrawn"].includes(stage)).map(([stage, count]) => <div key={stage}><div className="mb-2 flex justify-between text-sm"><span>{statusLabels[stage]}</span><span className="tabular-nums">{count}</span></div><progress aria-label={`${statusLabels[stage]} applicants`} max={Math.max(1, data.applications)} value={count} className="h-1.5 w-full" /></div>)}</div></section></div>
    <section className="mt-10 border-t pt-7"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Upcoming interviews</h2><Link href="/recruiter/interviews" className="text-sm text-primary">View interviews</Link></div>{!data.upcoming_interviews.length ? <p className="py-4 text-sm text-muted-foreground">No interviews scheduled.</p> : <div className="divide-y">{data.upcoming_interviews.map(i => <Link href={`/recruiter/interviews/${i.id}`} key={i.id} className="flex flex-wrap items-center gap-4 py-4"><CalendarDays className="size-5 text-primary" /><div className="flex-1"><h3 className="text-sm font-semibold">{i.candidate_name} · {i.title}</h3><p className="mt-1 text-xs text-muted-foreground">{i.job_title}</p></div><span className="text-sm">{formatDateTime(i.scheduled_at)}</span><ArrowRight className="size-4" /></Link>)}</div>}</section>
  </>}</LoadView>;
}
